"""
Merges REAL Razorpay customer/order data with SIMULATED fraud-relevant
behavioral features.

WHAT IS REAL: customer_id, order_id, amount, currency, timestamp -- all
genuinely issued by Razorpay's test-mode API (see
data/demo/razorpay_real_test_data.json, generated by
scripts/generate_razorpay_data.py).

WHAT IS SIMULATED: velocity_score, merchant_risk_score, cvv_retry_count,
and other fraud-relevant behavioral fields. Razorpay's Orders API has no
concept of these -- they don't exist in a real Order object. Values here
are sampled from credit_card_fraud_2026.csv's actual per-feature
distributions (same baseline stats already used in pattern_agent.py),
not arbitrary guesses.

State this distinction explicitly wherever this data is referenced --
never imply the behavioral features themselves are real Razorpay data.

One customer's most recent order is deliberately given elevated values
(velocity_score, cvv_retry_count) relative to their own simulated
history, specifically to demonstrate Agent 1's entity-drift mode
actually detecting something -- labeled clearly in the output.

Run with: python scripts/build_entity_demo_data.py
"""

import json
import random
from pathlib import Path

random.seed(42)

INPUT_FILE = Path("data/demo/razorpay_real_test_data.json")
OUTPUT_FILE = Path("data/demo/merged_entity_demo.json")

# Same baseline stats as pattern_agent.py, derived from the real dataset
BASELINE = {
    "velocity_score": (19.81, 12.37),
    "merchant_risk_score": (37.40, 17.06),
    "cvv_retry_count": (0.18, 0.42),
}

MERCHANT_CATEGORIES = ["Restaurants", "Online Retail", "Grocery Store", "Fuel Dispenser",
                        "Utilities", "Fast Food", "Drug Store", "Clothing Store"]
CARD_TYPES = ["Visa", "Mastercard"]
AUTH_METHODS = ["OTP", "3D Secure"]
CHANNELS = ["Online", "POS", "ATM"]
DEVICE_TYPES = ["Android Phone", "iPhone", "Windows Laptop", "Mac"]

DRIFT_CUSTOMER_INDEX = 0  # first customer's latest order gets deliberate drift


def sample_feature(key: str) -> float:
    mean, std = BASELINE[key]
    return max(0.0, random.gauss(mean, std))


def build_transaction(order: dict, customer: dict, order_index: int, is_drift_order: bool) -> dict:
    amount_inr = order["amount"] / 100  # paise -> rupees

    if is_drift_order:
        # Deliberately elevated relative to this customer's own typical
        # range, to demonstrate Agent 1's entity-drift mode.
        velocity_score = sample_feature("velocity_score") + 35
        cvv_retry_count = random.randint(3, 5)
    else:
        velocity_score = sample_feature("velocity_score")
        cvv_retry_count = random.choices([0, 1, 2], weights=[0.8, 0.15, 0.05])[0]

    return {
        "transaction_id": f"rzp-{order['id']}",
        "amount_usd": round(amount_inr, 2),  # field name kept for schema compatibility; value is INR
        "merchant_category": random.choice(MERCHANT_CATEGORIES),
        "card_type": random.choice(CARD_TYPES),
        "auth_method": random.choice(AUTH_METHODS),
        "channel": random.choice(CHANNELS),
        "device_type": random.choice(DEVICE_TYPES),
        "is_foreign_transaction": False,
        "hours_since_last_txn": round(random.uniform(1, 48), 2),
        "txn_count_last_24h": random.randint(1, 4),
        "distance_from_home_km": round(random.uniform(0, 40), 2),
        "card_age_months": random.randint(6, 60),
        "customer_age": random.randint(20, 55),
        "account_balance_usd": round(random.uniform(500, 5000), 2),
        "is_new_merchant": order_index == 0,
        "used_vpn": False,
        "ip_country_mismatch": False,
        "billing_shipping_mismatch": False,
        "cvv_retry_count": cvv_retry_count,
        "velocity_score": round(velocity_score, 2),
        "time_of_day_hour": random.randint(0, 23),
        "day_of_week": random.randint(0, 6),
        "is_ai_generated_scam_attempt": False,
        "merchant_risk_score": round(sample_feature("merchant_risk_score"), 2),
        "prior_disputes": 0,
        # Metadata, NOT part of the TransactionIn schema -- real Razorpay linkage
        "_real_razorpay_customer_id": customer["id"],
        "_real_razorpay_order_id": order["id"],
        "_is_deliberate_drift_demo_order": is_drift_order,
    }


def main():
    with open(INPUT_FILE) as f:
        raw = json.load(f)

    merged = []
    for c_idx, entry in enumerate(raw):
        customer = entry["customer"]
        orders = entry["orders"]
        card_group = []
        for o_idx, order in enumerate(orders):
            is_drift = (c_idx == DRIFT_CUSTOMER_INDEX and o_idx == len(orders) - 1)
            card_group.append(build_transaction(order, customer, o_idx, is_drift))
        merged.append({
            "real_razorpay_customer_id": customer["id"],
            "real_razorpay_customer_name": customer["name"],
            "transactions": card_group,
        })

    with open(OUTPUT_FILE, "w") as f:
        json.dump(merged, f, indent=2)

    drift_customer = raw[DRIFT_CUSTOMER_INDEX]["customer"]
    print(f"Merged {len(merged)} real customers with simulated behavioral features.")
    print(f"Deliberate drift demo: customer {drift_customer['id']} ({drift_customer['name']})'s "
          f"latest order has elevated velocity_score and cvv_retry_count vs. their own history.")
    print(f"Saved to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
